format = """
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$custom\
$package\
$deno\
$helm\
$kotlin\
$lua\
$nodejs\
$python\
$red\
$rust\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$line_break\
$time\
$status\
$shell\
$character
"""

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 750

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[custom.latest-release]
description = "Show latest git tag"
command = "git tag --sort=committerdate | tail -1"
style = "bold cyan"
symbol = "📦 "
when = """[ "$(git tag --sort=committerdate | tail -1)" != "" ]"""
format = "is [$symbol($output)]($style) "

